// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: apiKeys.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT
    name,
    "userId",
    permissions,
    "expiresAt",
    enabled,
    metadata
FROM
    apikey
WHERE
    KEY = $1
`

type GetAPIKeyByHashRow struct {
	Name        sql.NullString
	UserId      uuid.UUID
	Permissions sql.NullString
	ExpiresAt   sql.NullTime
	Enabled     sql.NullBool
	Metadata    sql.NullString
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, key string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, key)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.Name,
		&i.UserId,
		&i.Permissions,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
	)
	return i, err
}
