// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: collaborators.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCollaborator = `-- name: AddCollaborator :exec
INSERT INTO
    collaborators (contact_id, user_id, role)
VALUES
    ($1, $2, $3)
`

type AddCollaboratorParams struct {
	ContactID uuid.UUID
	UserID    uuid.UUID
	Role      string
}

func (q *Queries) AddCollaborator(ctx context.Context, arg AddCollaboratorParams) error {
	_, err := q.db.ExecContext(ctx, addCollaborator, arg.ContactID, arg.UserID, arg.Role)
	return err
}

const listCollaborators = `-- name: ListCollaborators :many
SELECT
    u.id,
    u.name,
    c.role
FROM
    collaborators c
    JOIN users u ON c.user_id = u.id
WHERE
    c.contact_id = $1
`

type ListCollaboratorsRow struct {
	ID   uuid.UUID
	Name string
	Role string
}

func (q *Queries) ListCollaborators(ctx context.Context, contactID uuid.UUID) ([]ListCollaboratorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollaborators, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollaboratorsRow
	for rows.Next() {
		var i ListCollaboratorsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollaborator = `-- name: RemoveCollaborator :exec
DELETE FROM
    collaborators
WHERE
    contact_id = $1
    AND user_id = $2
`

type RemoveCollaboratorParams struct {
	ContactID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveCollaborator(ctx context.Context, arg RemoveCollaboratorParams) error {
	_, err := q.db.ExecContext(ctx, removeCollaborator, arg.ContactID, arg.UserID)
	return err
}
