// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contactLogs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getContactLogsByContactID = `-- name: GetContactLogsByContactID :many
SELECT
    cl.id, cl.contact_id, cl.contact_method, cl.created_by, cl.note, cl.created_at, cl.updated_at,
    u.name AS created_by_name
FROM
    contact_logs cl
    JOIN users u ON u.id = cl.created_by
WHERE
    cl.contact_id = $1
ORDER BY
    cl.created_at DESC
`

type GetContactLogsByContactIDRow struct {
	ID            uuid.UUID
	ContactID     uuid.NullUUID
	ContactMethod string
	CreatedBy     uuid.NullUUID
	Note          sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	CreatedByName string
}

func (q *Queries) GetContactLogsByContactID(ctx context.Context, contactID uuid.NullUUID) ([]GetContactLogsByContactIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactLogsByContactID, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContactLogsByContactIDRow
	for rows.Next() {
		var i GetContactLogsByContactIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.ContactMethod,
			&i.CreatedBy,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logContact = `-- name: LogContact :one
WITH inserted AS (
    INSERT INTO
        contact_logs(contact_id, contact_method, created_by, note)
    VALUES
        ($1, $2, $3, $4)
    RETURNING
        id, contact_id, contact_method, created_by, note, created_at, updated_at
),
updated AS (
    UPDATE
        contacts
    SET
        last_contacted_at = NOW()
    WHERE
        id = $1
    RETURNING
        id
)
SELECT
    id, contact_id, contact_method, created_by, note, created_at, updated_at
FROM
    inserted
`

type LogContactParams struct {
	ContactID     uuid.NullUUID
	ContactMethod string
	CreatedBy     uuid.NullUUID
	Note          sql.NullString
}

type LogContactRow struct {
	ID            uuid.UUID
	ContactID     uuid.NullUUID
	ContactMethod string
	CreatedBy     uuid.NullUUID
	Note          sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

func (q *Queries) LogContact(ctx context.Context, arg LogContactParams) (LogContactRow, error) {
	row := q.db.QueryRowContext(ctx, logContact,
		arg.ContactID,
		arg.ContactMethod,
		arg.CreatedBy,
		arg.Note,
	)
	var i LogContactRow
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.ContactMethod,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
