// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: emails.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkEnterEmails = `-- name: BulkEnterEmails :exec
INSERT INTO
    emails (contact_id, email, TYPE, is_primary)
SELECT
    unnest($1::uuid []),
    unnest($2::text []),
    unnest($3::text []),
    unnest($4::boolean [])
`

type BulkEnterEmailsParams struct {
	ContactIds []uuid.UUID
	Emails     []string
	Types      []string
	IsPrimary  []bool
}

func (q *Queries) BulkEnterEmails(ctx context.Context, arg BulkEnterEmailsParams) error {
	_, err := q.db.ExecContext(ctx, bulkEnterEmails,
		pq.Array(arg.ContactIds),
		pq.Array(arg.Emails),
		pq.Array(arg.Types),
		pq.Array(arg.IsPrimary),
	)
	return err
}

const enterEmail = `-- name: EnterEmail :exec
INSERT INTO
    emails (contact_id, email_address, TYPE, is_primary)
VALUES
    ($1, $2, $3, $4)
`

type EnterEmailParams struct {
	ContactID    uuid.NullUUID
	EmailAddress string
	Type         sql.NullString
	IsPrimary    sql.NullBool
}

func (q *Queries) EnterEmail(ctx context.Context, arg EnterEmailParams) error {
	_, err := q.db.ExecContext(ctx, enterEmail,
		arg.ContactID,
		arg.EmailAddress,
		arg.Type,
		arg.IsPrimary,
	)
	return err
}

const testBulkInsertEmails = `-- name: TestBulkInsertEmails :exec
INSERT INTO
    emails (contact_id, email_address, TYPE, is_primary)
SELECT
    e.contact_id,
    e.email_address,
    e.type,
    e.is_primary
FROM
    jsonb_to_recordset($1::jsonb) AS e(
        contact_id uuid,
        email_address text,
        TYPE text,
        is_primary boolean
    )
`

func (q *Queries) TestBulkInsertEmails(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, testBulkInsertEmails, dollar_1)
	return err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE
    emails
SET
    is_verified = TRUE,
    is_subscribed = TRUE
WHERE
    email_address = $1
RETURNING
    id, contact_id, email_address, type, is_primary, created_at, updated_at, is_verified, is_subscribed
`

func (q *Queries) VerifyEmail(ctx context.Context, emailAddress string) error {
	_, err := q.db.ExecContext(ctx, verifyEmail, emailAddress)
	return err
}
