// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: goals.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteGoal = `-- name: DeleteGoal :one
DELETE FROM
    goals
WHERE
    id = $1
RETURNING
    id, user_id, year, month, income_goal, transaction_goal, estimated_average_sale_price, estimated_average_commission_rate, created_at, updated_at
`

func (q *Queries) DeleteGoal(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRowContext(ctx, deleteGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.IncomeGoal,
		&i.TransactionGoal,
		&i.EstimatedAverageSalePrice,
		&i.EstimatedAverageCommissionRate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoalByUserAndYear = `-- name: GetGoalByUserAndYear :one
SELECT
    id, user_id, year, month, income_goal, transaction_goal, estimated_average_sale_price, estimated_average_commission_rate, created_at, updated_at
FROM
    goals
WHERE
    user_id = $1
    AND year = $2
`

type GetGoalByUserAndYearParams struct {
	UserID uuid.NullUUID
	Year   int32
}

func (q *Queries) GetGoalByUserAndYear(ctx context.Context, arg GetGoalByUserAndYearParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoalByUserAndYear, arg.UserID, arg.Year)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.IncomeGoal,
		&i.TransactionGoal,
		&i.EstimatedAverageSalePrice,
		&i.EstimatedAverageCommissionRate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGoal = `-- name: SetGoal :one
INSERT INTO
    goals (
        user_id,
        year,
        MONTH,
        income_goal,
        transaction_goal,
        estimated_average_sale_price,
        estimated_average_commission_rate
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
RETURNING
    id, user_id, year, month, income_goal, transaction_goal, estimated_average_sale_price, estimated_average_commission_rate, created_at, updated_at
`

type SetGoalParams struct {
	UserID                         uuid.NullUUID
	Year                           int32
	Month                          int32
	IncomeGoal                     sql.NullString
	TransactionGoal                sql.NullInt32
	EstimatedAverageSalePrice      sql.NullString
	EstimatedAverageCommissionRate sql.NullString
}

func (q *Queries) SetGoal(ctx context.Context, arg SetGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, setGoal,
		arg.UserID,
		arg.Year,
		arg.Month,
		arg.IncomeGoal,
		arg.TransactionGoal,
		arg.EstimatedAverageSalePrice,
		arg.EstimatedAverageCommissionRate,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.IncomeGoal,
		&i.TransactionGoal,
		&i.EstimatedAverageSalePrice,
		&i.EstimatedAverageCommissionRate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE
    goals
SET
    income_goal = $2,
    transaction_goal = $3,
    estimated_average_sale_price = $4,
    estimated_average_commission_rate = $5
WHERE
    id = $1
RETURNING
    id, user_id, year, month, income_goal, transaction_goal, estimated_average_sale_price, estimated_average_commission_rate, created_at, updated_at
`

type UpdateGoalParams struct {
	ID                             uuid.UUID
	IncomeGoal                     sql.NullString
	TransactionGoal                sql.NullInt32
	EstimatedAverageSalePrice      sql.NullString
	EstimatedAverageCommissionRate sql.NullString
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.ID,
		arg.IncomeGoal,
		arg.TransactionGoal,
		arg.EstimatedAverageSalePrice,
		arg.EstimatedAverageCommissionRate,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Year,
		&i.Month,
		&i.IncomeGoal,
		&i.TransactionGoal,
		&i.EstimatedAverageSalePrice,
		&i.EstimatedAverageCommissionRate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
