// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: members.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getOrganizationMembers = `-- name: GetOrganizationMembers :many
SELECT
    id,
    "userId",
    role
FROM
    member
WHERE
    "organizationId" = $1
`

type GetOrganizationMembersRow struct {
	ID     uuid.UUID
	UserId uuid.UUID
	Role   string
}

func (q *Queries) GetOrganizationMembers(ctx context.Context, organizationid uuid.UUID) ([]GetOrganizationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrganizationMembers, organizationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrganizationMembersRow
	for rows.Next() {
		var i GetOrganizationMembersRow
		if err := rows.Scan(&i.ID, &i.UserId, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
