// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AppointmentOutcome string

const (
	AppointmentOutcomeNoOutcome   AppointmentOutcome = "no-outcome"
	AppointmentOutcomeNo          AppointmentOutcome = "no"
	AppointmentOutcomeYes         AppointmentOutcome = "yes"
	AppointmentOutcomeRescheduled AppointmentOutcome = "rescheduled"
	AppointmentOutcomeCancelled   AppointmentOutcome = "cancelled"
	AppointmentOutcomeNoShow      AppointmentOutcome = "no-show"
)

func (e *AppointmentOutcome) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentOutcome(s)
	case string:
		*e = AppointmentOutcome(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentOutcome: %T", src)
	}
	return nil
}

type NullAppointmentOutcome struct {
	AppointmentOutcome AppointmentOutcome
	Valid              bool // Valid is true if AppointmentOutcome is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentOutcome) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentOutcome, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentOutcome.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentOutcome) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentOutcome), nil
}

type AppointmentType string

const (
	AppointmentTypeListingAppointment AppointmentType = "Listing-appointment"
	AppointmentTypeBuyerAppointment   AppointmentType = "Buyer-appointment"
	AppointmentTypeNoType             AppointmentType = "no-type"
)

func (e *AppointmentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentType(s)
	case string:
		*e = AppointmentType(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentType: %T", src)
	}
	return nil
}

type NullAppointmentType struct {
	AppointmentType AppointmentType
	Valid           bool // Valid is true if AppointmentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentType) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentType), nil
}

type ClientType string

const (
	ClientTypeBuyer  ClientType = "buyer"
	ClientTypeSeller ClientType = "seller"
)

func (e *ClientType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClientType(s)
	case string:
		*e = ClientType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClientType: %T", src)
	}
	return nil
}

type NullClientType struct {
	ClientType ClientType
	Valid      bool // Valid is true if ClientType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClientType) Scan(value interface{}) error {
	if value == nil {
		ns.ClientType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClientType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClientType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClientType), nil
}

type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityNormal TaskPriority = "normal"
	TaskPriorityHigh   TaskPriority = "high"
)

func (e *TaskPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskPriority(s)
	case string:
		*e = TaskPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskPriority: %T", src)
	}
	return nil
}

type NullTaskPriority struct {
	TaskPriority TaskPriority
	Valid        bool // Valid is true if TaskPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TaskPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskPriority), nil
}

type TaskStatus string

const (
	TaskStatusPending   TaskStatus = "pending"
	TaskStatusCompleted TaskStatus = "completed"
	TaskStatusCancelled TaskStatus = "cancelled"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypeCall      TaskType = "call"
	TaskTypeEmail     TaskType = "email"
	TaskTypeFollowUp  TaskType = "follow-up"
	TaskTypeText      TaskType = "text"
	TaskTypeShowing   TaskType = "showing"
	TaskTypeClosing   TaskType = "closing"
	TaskTypeOpenHouse TaskType = "open-house"
	TaskTypeThankYou  TaskType = "thank-you"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType
	Valid    bool // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type Account struct {
	ID                    uuid.UUID
	AccountId             string
	ProviderId            string
	UserId                uuid.UUID
	AccessToken           sql.NullString
	RefreshToken          sql.NullString
	IdToken               sql.NullString
	AccessTokenExpiresAt  sql.NullTime
	RefreshTokenExpiresAt sql.NullTime
	Scope                 sql.NullString
	Password              sql.NullString
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type Apikey struct {
	ID                  uuid.UUID
	Name                sql.NullString
	Start               sql.NullString
	Prefix              sql.NullString
	Key                 string
	UserId              uuid.UUID
	RefillInterval      sql.NullInt32
	RefillAmount        sql.NullInt32
	LastRefillAt        sql.NullTime
	Enabled             sql.NullBool
	RateLimitEnabled    sql.NullBool
	RateLimitTimeWindow sql.NullInt32
	RateLimitMax        sql.NullInt32
	RequestCount        sql.NullInt32
	Remaining           sql.NullInt32
	LastRequest         sql.NullTime
	ExpiresAt           sql.NullTime
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Permissions         sql.NullString
	Metadata            sql.NullString
}

type Appointment struct {
	ID           uuid.UUID
	ContactID    uuid.NullUUID
	AssignedToID uuid.NullUUID
	Title        string
	ScheduledAt  time.Time
	Location     sql.NullString
	Type         NullAppointmentType
	Outcome      NullAppointmentOutcome
	Note         sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Collaborator struct {
	ID        uuid.UUID
	ContactID uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Contact struct {
	ID              uuid.UUID
	FirstName       string
	LastName        string
	Birthdate       sql.NullTime
	Source          sql.NullString
	Status          sql.NullString
	Address         sql.NullString
	City            sql.NullString
	State           sql.NullString
	ZipCode         sql.NullString
	Lender          sql.NullString
	PriceRange      sql.NullString
	Timeframe       sql.NullString
	OwnerID         uuid.NullUUID
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	LastContactedAt sql.NullTime
}

type ContactLog struct {
	ID            uuid.UUID
	ContactID     uuid.NullUUID
	ContactMethod string
	CreatedBy     uuid.NullUUID
	Note          sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type ContactNote struct {
	ID        uuid.UUID
	ContactID uuid.NullUUID
	Note      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	CreatedBy uuid.NullUUID
}

type ContactTag struct {
	ContactID uuid.UUID
	TagID     uuid.UUID
}

type Deal struct {
	ID                   uuid.UUID
	ContactID            uuid.NullUUID
	AssignedToID         uuid.NullUUID
	Title                string
	Price                int32
	ClosingDate          sql.NullTime
	EarnestMoneyDueDate  sql.NullTime
	MutualAcceptanceDate sql.NullTime
	InspectionDate       sql.NullTime
	AppraisalDate        sql.NullTime
	FinalWalkthroughDate sql.NullTime
	PossessionDate       sql.NullTime
	Commission           sql.NullString
	CommissionSplit      sql.NullString
	PropertyAddress      sql.NullString
	PropertyCity         sql.NullString
	PropertyState        sql.NullString
	PropertyZipCode      sql.NullString
	Description          sql.NullString
	StageID              uuid.NullUUID
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	ClosedDate           sql.NullTime
}

type Email struct {
	ID           uuid.UUID
	ContactID    uuid.NullUUID
	EmailAddress string
	Type         sql.NullString
	IsPrimary    sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	IsVerified   sql.NullBool
	IsSubscribed sql.NullBool
}

type Goal struct {
	ID                             uuid.UUID
	UserID                         uuid.NullUUID
	Year                           int32
	Month                          int32
	IncomeGoal                     sql.NullString
	TransactionGoal                sql.NullInt32
	EstimatedAverageSalePrice      sql.NullString
	EstimatedAverageCommissionRate sql.NullString
	CreatedAt                      sql.NullTime
	UpdatedAt                      sql.NullTime
}

type Invitation struct {
	ID             uuid.UUID
	OrganizationId uuid.UUID
	Email          string
	Role           sql.NullString
	Status         string
	ExpiresAt      time.Time
	CreatedAt      time.Time
	InviterId      uuid.UUID
}

type Member struct {
	ID             uuid.UUID
	OrganizationId uuid.UUID
	UserId         uuid.UUID
	Role           string
	CreatedAt      time.Time
}

type Notification struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Type          string
	Message       string
	ContactID     uuid.NullUUID
	AppointmentID uuid.NullUUID
	TaskID        uuid.NullUUID
	Read          sql.NullBool
	CreatedAt     sql.NullTime
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Logo      sql.NullString
	CreatedAt time.Time
	Metadata  sql.NullString
}

type Passkey struct {
	ID           uuid.UUID
	Name         sql.NullString
	PublicKey    string
	UserId       uuid.UUID
	CredentialID string
	Counter      int32
	DeviceType   string
	BackedUp     bool
	Transports   sql.NullString
	CreatedAt    sql.NullTime
	Aaguid       sql.NullString
}

type PhoneNumber struct {
	ID          uuid.UUID
	ContactID   uuid.NullUUID
	PhoneNumber string
	Type        sql.NullString
	IsPrimary   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Session struct {
	ID                   uuid.UUID
	ExpiresAt            time.Time
	Token                string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	IpAddress            sql.NullString
	UserAgent            sql.NullString
	UserId               uuid.UUID
	ImpersonatedBy       uuid.NullUUID
	ActiveOrganizationId uuid.NullUUID
}

type SmartList struct {
	ID             uuid.UUID
	Name           string
	Description    sql.NullString
	UserID         uuid.NullUUID
	FilterCriteria pqtype.NullRawMessage
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Stage struct {
	ID                   uuid.UUID
	Name                 string
	Description          sql.NullString
	ClientType           ClientType
	NumberOfDeals        sql.NullInt32
	TotalPotentialIncome sql.NullInt32
	OrderIndex           int32
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	OwnerID              uuid.NullUUID
}

type Subscription struct {
	ID                   uuid.UUID
	Plan                 string
	ReferenceId          uuid.UUID
	StripeCustomerId     sql.NullString
	StripeSubscriptionId sql.NullString
	Status               string
	PeriodStart          sql.NullTime
	PeriodEnd            sql.NullTime
	CancelAtPeriodEnd    sql.NullBool
	Seats                sql.NullInt32
	TrialStart           sql.NullTime
	TrialEnd             sql.NullTime
}

type Tag struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	UserID      uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Task struct {
	ID           uuid.UUID
	ContactID    uuid.NullUUID
	AssignedToID uuid.NullUUID
	Title        string
	Type         NullTaskType
	Date         sql.NullTime
	Status       NullTaskStatus
	Priority     NullTaskPriority
	Note         sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type TwoFactor struct {
	ID          uuid.UUID
	Secret      string
	BackupCodes string
	UserId      uuid.UUID
}

type User struct {
	ID               uuid.UUID
	Name             string
	Email            string
	EmailVerified    bool
	Image            sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
	TwoFactorEnabled sql.NullBool
	Role             sql.NullString
	Banned           sql.NullBool
	BanReason        sql.NullString
	BanExpires       sql.NullTime
	StripeCustomerId sql.NullString
	TrialAllowed     bool
}

type Verification struct {
	ID         uuid.UUID
	Identifier string
	Value      string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
