// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO
    contact_notes (
        contact_id,
        note,
        created_by
    )
VALUES
    ($1, $2, $3)
RETURNING
    id, contact_id, note, created_at, updated_at, created_by
`

type CreateNoteParams struct {
	ContactID uuid.NullUUID
	Note      string
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (ContactNote, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.ContactID, arg.Note, arg.CreatedBy)
	var i ContactNote
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getNotesByContactID = `-- name: GetNotesByContactID :many
SELECT
    id, contact_id, note, created_at, updated_at, created_by
FROM
    contact_notes
WHERE
    contact_id = $1
ORDER BY
    created_at DESC
`

func (q *Queries) GetNotesByContactID(ctx context.Context, contactID uuid.NullUUID) ([]ContactNote, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByContactID, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactNote
	for rows.Next() {
		var i ContactNote
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
