// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notes.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createNote = `-- name: CreateNote :one
INSERT INTO
    contact_notes (
        contact_id,
        note,
        created_by
    )
VALUES
    ($1, $2, $3)
RETURNING
    id, contact_id, note, created_at, updated_at, created_by
`

type CreateNoteParams struct {
	ContactID uuid.NullUUID
	Note      string
	CreatedBy uuid.NullUUID
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (ContactNote, error) {
	row := q.db.QueryRowContext(ctx, createNote, arg.ContactID, arg.Note, arg.CreatedBy)
	var i ContactNote
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getNotesByContactID = `-- name: GetNotesByContactID :many
SELECT
    cn.id, cn.contact_id, cn.note, cn.created_at, cn.updated_at, cn.created_by,
    u.name AS created_by_name
FROM
    contact_notes cn
    JOIN users u ON u.id = cn.created_by
WHERE
    cn.contact_id = $1
ORDER BY
    cn.created_at DESC
`

type GetNotesByContactIDRow struct {
	ID            uuid.UUID
	ContactID     uuid.NullUUID
	Note          string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	CreatedBy     uuid.NullUUID
	CreatedByName string
}

func (q *Queries) GetNotesByContactID(ctx context.Context, contactID uuid.NullUUID) ([]GetNotesByContactIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByContactID, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNotesByContactIDRow
	for rows.Next() {
		var i GetNotesByContactIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
