// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO
    notifications (
        user_id,
        TYPE,
        message,
        contact_id,
        appointment_id,
        task_id
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
RETURNING
    id, user_id, type, message, contact_id, appointment_id, task_id, read, created_at
`

type CreateNotificationParams struct {
	UserID        uuid.UUID
	Type          string
	Message       string
	ContactID     uuid.NullUUID
	AppointmentID uuid.NullUUID
	TaskID        uuid.NullUUID
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Message,
		arg.ContactID,
		arg.AppointmentID,
		arg.TaskID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Message,
		&i.ContactID,
		&i.AppointmentID,
		&i.TaskID,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM
    notifications
WHERE
    id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const getNotificationsByUserID = `-- name: GetNotificationsByUserID :many
SELECT
    id, user_id, type, message, contact_id, appointment_id, task_id, read, created_at
FROM
    notifications
WHERE
    user_id = $1
ORDER BY
    created_at DESC
LIMIT
    $2 OFFSET $3
`

type GetNotificationsByUserIDParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetNotificationsByUserID(ctx context.Context, arg GetNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.ContactID,
			&i.AppointmentID,
			&i.TaskID,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE
    notifications
SET
    READ = TRUE
WHERE
    user_id = $1
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE
    notifications
SET
    READ = TRUE
WHERE
    id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, id)
	return err
}
