// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: phoneNumbers.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const bulkEnterPhoneNumbers = `-- name: BulkEnterPhoneNumbers :exec
INSERT INTO
    phone_numbers (contact_id, phone_number, TYPE, is_primary)
SELECT
    unnest($1::uuid []),
    unnest($2::text []),
    unnest($3::text []),
    unnest($4::boolean [])
`

type BulkEnterPhoneNumbersParams struct {
	ContactIds   []uuid.UUID
	PhoneNumbers []string
	Types        []string
	IsPrimary    []bool
}

func (q *Queries) BulkEnterPhoneNumbers(ctx context.Context, arg BulkEnterPhoneNumbersParams) error {
	_, err := q.db.ExecContext(ctx, bulkEnterPhoneNumbers,
		pq.Array(arg.ContactIds),
		pq.Array(arg.PhoneNumbers),
		pq.Array(arg.Types),
		pq.Array(arg.IsPrimary),
	)
	return err
}

const deletePhoneNumber = `-- name: DeletePhoneNumber :exec
DELETE FROM
    phone_numbers
WHERE
    id = $1
`

func (q *Queries) DeletePhoneNumber(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePhoneNumber, id)
	return err
}

const enterPhoneNumber = `-- name: EnterPhoneNumber :exec
INSERT INTO
    phone_numbers (contact_id, phone_number, TYPE, is_primary)
VALUES
    ($1, $2, $3, $4)
`

type EnterPhoneNumberParams struct {
	ContactID   uuid.NullUUID
	PhoneNumber string
	Type        sql.NullString
	IsPrimary   sql.NullBool
}

func (q *Queries) EnterPhoneNumber(ctx context.Context, arg EnterPhoneNumberParams) error {
	_, err := q.db.ExecContext(ctx, enterPhoneNumber,
		arg.ContactID,
		arg.PhoneNumber,
		arg.Type,
		arg.IsPrimary,
	)
	return err
}

const getPhoneNumberByID = `-- name: GetPhoneNumberByID :one
SELECT
    id, contact_id, phone_number, type, is_primary, created_at, updated_at
FROM
    phone_numbers
WHERE
    id = $1
`

func (q *Queries) GetPhoneNumberByID(ctx context.Context, id uuid.UUID) (PhoneNumber, error) {
	row := q.db.QueryRowContext(ctx, getPhoneNumberByID, id)
	var i PhoneNumber
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.PhoneNumber,
		&i.Type,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneNumbersByContactID = `-- name: GetPhoneNumbersByContactID :many
SELECT
    id, contact_id, phone_number, type, is_primary, created_at, updated_at
FROM
    phone_numbers
WHERE
    contact_id = $1
ORDER BY
    is_primary DESC,
    created_at DESC
`

func (q *Queries) GetPhoneNumbersByContactID(ctx context.Context, contactID uuid.NullUUID) ([]PhoneNumber, error) {
	rows, err := q.db.QueryContext(ctx, getPhoneNumbersByContactID, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhoneNumber
	for rows.Next() {
		var i PhoneNumber
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.PhoneNumber,
			&i.Type,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const testBulkInsertPhoneNumbers = `-- name: TestBulkInsertPhoneNumbers :exec
INSERT INTO
    phone_numbers (contact_id, number, TYPE, is_primary)
SELECT
    p.contact_id,
    p.number,
    p.type,
    p.is_primary
FROM
    jsonb_to_recordset($1::jsonb) AS p(
        contact_id uuid,
        number text,
        TYPE text,
        is_primary boolean
    )
`

func (q *Queries) TestBulkInsertPhoneNumbers(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, testBulkInsertPhoneNumbers, dollar_1)
	return err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
UPDATE
    phone_numbers
SET
    phone_number = $1,
    TYPE = $2,
    is_primary = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $4
`

type UpdatePhoneNumberParams struct {
	PhoneNumber string
	Type        sql.NullString
	IsPrimary   sql.NullBool
	ID          uuid.UUID
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoneNumber,
		arg.PhoneNumber,
		arg.Type,
		arg.IsPrimary,
		arg.ID,
	)
	return err
}
