// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: s3.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserImage = `-- name: GetUserImage :one
SELECT
    image
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserImage(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserImage, id)
	var image sql.NullString
	err := row.Scan(&image)
	return image, err
}

const updateUserImage = `-- name: UpdateUserImage :exec
UPDATE
    users
SET
    image = $2
WHERE
    id = $1
`

type UpdateUserImageParams struct {
	ID    uuid.UUID
	Image sql.NullString
}

func (q *Queries) UpdateUserImage(ctx context.Context, arg UpdateUserImageParams) error {
	_, err := q.db.ExecContext(ctx, updateUserImage, arg.ID, arg.Image)
	return err
}
