// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: smart_list.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createSmartList = `-- name: CreateSmartList :one
INSERT INTO
    smart_lists (
        name,
        description,
        user_id
    )
VALUES
    ($1, $2, $3)
RETURNING
    id, name, description, user_id, filter_criteria, created_at, updated_at
`

type CreateSmartListParams struct {
	Name        string
	Description sql.NullString
	UserID      uuid.NullUUID
}

func (q *Queries) CreateSmartList(ctx context.Context, arg CreateSmartListParams) (SmartList, error) {
	row := q.db.QueryRowContext(ctx, createSmartList, arg.Name, arg.Description, arg.UserID)
	var i SmartList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.FilterCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllSmartLists = `-- name: GetAllSmartLists :many
SELECT
    id, name, description, user_id, filter_criteria, created_at, updated_at
FROM
    smart_lists
WHERE
    user_id = $1
`

func (q *Queries) GetAllSmartLists(ctx context.Context, userID uuid.NullUUID) ([]SmartList, error) {
	rows, err := q.db.QueryContext(ctx, getAllSmartLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmartList
	for rows.Next() {
		var i SmartList
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.FilterCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSmartListFilterCriteria = `-- name: SetSmartListFilterCriteria :one
UPDATE
    smart_lists
SET
    filter_criteria = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, name, description, user_id, filter_criteria, created_at, updated_at
`

type SetSmartListFilterCriteriaParams struct {
	ID             uuid.UUID
	FilterCriteria pqtype.NullRawMessage
}

func (q *Queries) SetSmartListFilterCriteria(ctx context.Context, arg SetSmartListFilterCriteriaParams) (SmartList, error) {
	row := q.db.QueryRowContext(ctx, setSmartListFilterCriteria, arg.ID, arg.FilterCriteria)
	var i SmartList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.FilterCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSmartList = `-- name: UpdateSmartList :one
UPDATE
    smart_lists
SET
    name = $2,
    description = $3,
    filter_criteria = $4,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, name, description, user_id, filter_criteria, created_at, updated_at
`

type UpdateSmartListParams struct {
	ID             uuid.UUID
	Name           string
	Description    sql.NullString
	FilterCriteria pqtype.NullRawMessage
}

func (q *Queries) UpdateSmartList(ctx context.Context, arg UpdateSmartListParams) (SmartList, error) {
	row := q.db.QueryRowContext(ctx, updateSmartList,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.FilterCriteria,
	)
	var i SmartList
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.FilterCriteria,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
