// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stages.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStage = `-- name: CreateStage :one
INSERT INTO
    stages (
        name,
        description,
        client_type,
        order_index,
        owner_id
    )
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, name, description, client_type, number_of_deals, total_potential_income, order_index, created_at, updated_at, owner_id
`

type CreateStageParams struct {
	Name        string
	Description sql.NullString
	ClientType  ClientType
	OrderIndex  int32
	OwnerID     uuid.NullUUID
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, createStage,
		arg.Name,
		arg.Description,
		arg.ClientType,
		arg.OrderIndex,
		arg.OwnerID,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientType,
		&i.NumberOfDeals,
		&i.TotalPotentialIncome,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :exec
DELETE FROM
    stages
WHERE
    id = $1
`

func (q *Queries) DeleteStage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStage, id)
	return err
}

const getAllStages = `-- name: GetAllStages :many
SELECT
    id, name, description, client_type, number_of_deals, total_potential_income, order_index, created_at, updated_at, owner_id
FROM
    stages
WHERE
    owner_id = $1
ORDER BY
    client_type ASC,
    order_index ASC
`

func (q *Queries) GetAllStages(ctx context.Context, ownerID uuid.NullUUID) ([]Stage, error) {
	rows, err := q.db.QueryContext(ctx, getAllStages, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientType,
			&i.NumberOfDeals,
			&i.TotalPotentialIncome,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStageByID = `-- name: GetStageByID :one
SELECT
    id, name, description, client_type, number_of_deals, total_potential_income, order_index, created_at, updated_at, owner_id
FROM
    stages
WHERE
    id = $1
`

func (q *Queries) GetStageByID(ctx context.Context, id uuid.UUID) (Stage, error) {
	row := q.db.QueryRowContext(ctx, getStageByID, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientType,
		&i.NumberOfDeals,
		&i.TotalPotentialIncome,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}

const getStagesByClientType = `-- name: GetStagesByClientType :many
SELECT
    id, name, description, client_type, number_of_deals, total_potential_income, order_index, created_at, updated_at, owner_id
FROM
    stages
WHERE
    client_type = $1
    AND owner_id = $2
ORDER BY
    order_index ASC
`

type GetStagesByClientTypeParams struct {
	ClientType ClientType
	OwnerID    uuid.NullUUID
}

func (q *Queries) GetStagesByClientType(ctx context.Context, arg GetStagesByClientTypeParams) ([]Stage, error) {
	rows, err := q.db.QueryContext(ctx, getStagesByClientType, arg.ClientType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stage
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientType,
			&i.NumberOfDeals,
			&i.TotalPotentialIncome,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStage = `-- name: UpdateStage :one
UPDATE
    stages
SET
    name = $2,
    description = $3,
    client_type = $4,
    order_index = $5
WHERE
    id = $1
RETURNING
    id, name, description, client_type, number_of_deals, total_potential_income, order_index, created_at, updated_at, owner_id
`

type UpdateStageParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	ClientType  ClientType
	OrderIndex  int32
}

func (q *Queries) UpdateStage(ctx context.Context, arg UpdateStageParams) (Stage, error) {
	row := q.db.QueryRowContext(ctx, updateStage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ClientType,
		arg.OrderIndex,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientType,
		&i.NumberOfDeals,
		&i.TotalPotentialIncome,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
	)
	return i, err
}
