// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const assignTagToContact = `-- name: AssignTagToContact :one
INSERT INTO
    contact_tags(tag_id, contact_id)
VALUES
    ($1, $2)
RETURNING
    contact_id, tag_id
`

type AssignTagToContactParams struct {
	TagID     uuid.UUID
	ContactID uuid.UUID
}

func (q *Queries) AssignTagToContact(ctx context.Context, arg AssignTagToContactParams) (ContactTag, error) {
	row := q.db.QueryRowContext(ctx, assignTagToContact, arg.TagID, arg.ContactID)
	var i ContactTag
	err := row.Scan(&i.ContactID, &i.TagID)
	return i, err
}

const assignTagsToContact = `-- name: AssignTagsToContact :exec
WITH input_tags AS (
    SELECT
        unnest($2::text []) AS tag_name
),
inserted_tags AS (
    INSERT INTO
        tags(name, user_id)
    SELECT
        tag_name,
        $1
    FROM
        input_tags ON conflict ON CONSTRAINT unique_user_tag DO nothing
    RETURNING
        id,
        name
),
all_tags AS (
    SELECT
        id,
        name
    FROM
        inserted_tags
    UNION
    SELECT
        id,
        name
    FROM
        tags t
    WHERE
        t.name IN (
            SELECT
                tag_name
            FROM
                input_tags
        )
)
INSERT INTO
    contact_tags(contact_id, tag_id)
SELECT
    $3,
    id
FROM
    all_tags ON conflict DO nothing
`

type AssignTagsToContactParams struct {
	UserID    uuid.NullUUID
	Column2   []string
	ContactID uuid.UUID
}

func (q *Queries) AssignTagsToContact(ctx context.Context, arg AssignTagsToContactParams) error {
	_, err := q.db.ExecContext(ctx, assignTagsToContact, arg.UserID, pq.Array(arg.Column2), arg.ContactID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO
    tags (
        name,
        description,
        user_id
    )
VALUES
    ($1, $2, $3)
RETURNING
    id, name, description, user_id, created_at, updated_at
`

type CreateTagParams struct {
	Name        string
	Description sql.NullString
	UserID      uuid.NullUUID
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Description, arg.UserID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM
    tags
WHERE
    id = $1
RETURNING
    id, name, description, user_id, created_at, updated_at
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getAllTags = `-- name: GetAllTags :many
SELECT
    id, name, description, user_id, created_at, updated_at
FROM
    tags
WHERE
    user_id = $1
`

func (q *Queries) GetAllTags(ctx context.Context, userID uuid.NullUUID) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getAllTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromContact = `-- name: RemoveTagFromContact :exec
DELETE FROM
    contact_tags
WHERE
    tag_id = $1
    AND contact_id = $2
`

type RemoveTagFromContactParams struct {
	TagID     uuid.UUID
	ContactID uuid.UUID
}

func (q *Queries) RemoveTagFromContact(ctx context.Context, arg RemoveTagFromContactParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromContact, arg.TagID, arg.ContactID)
	return err
}

const testBulkAssignTagsToContacts = `-- name: TestBulkAssignTagsToContacts :exec
INSERT INTO
    contact_tags (contact_id, user_id, tag)
SELECT
    t.contact_id,
    t.user_id,
    t.tag
FROM
    jsonb_to_recordset($1::jsonb) AS t(
        contact_id uuid,
        user_id uuid,
        tag text
    )
`

func (q *Queries) TestBulkAssignTagsToContacts(ctx context.Context, dollar_1 json.RawMessage) error {
	_, err := q.db.ExecContext(ctx, testBulkAssignTagsToContacts, dollar_1)
	return err
}
