// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: Task.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO
    tasks (
        contact_id,
        assigned_to_id,
        title,
        TYPE,
        date,
        STATUS,
        priority,
        note
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
`

type CreateTaskParams struct {
	ContactID    uuid.NullUUID
	AssignedToID uuid.NullUUID
	Title        string
	Type         NullTaskType
	Date         sql.NullTime
	Status       NullTaskStatus
	Priority     NullTaskPriority
	Note         sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ContactID,
		arg.AssignedToID,
		arg.Title,
		arg.Type,
		arg.Date,
		arg.Status,
		arg.Priority,
		arg.Note,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AssignedToID,
		&i.Title,
		&i.Type,
		&i.Date,
		&i.Status,
		&i.Priority,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM
    tasks
WHERE
    id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getOverdueTasks = `-- name: GetOverdueTasks :many
SELECT
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
FROM
    tasks
WHERE
    date::date < current_date
    AND STATUS != 'completed'
    AND assigned_to_id = $1
ORDER BY
    date DESC
`

func (q *Queries) GetOverdueTasks(ctx context.Context, assignedToID uuid.NullUUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getOverdueTasks, assignedToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AssignedToID,
			&i.Title,
			&i.Type,
			&i.Date,
			&i.Status,
			&i.Priority,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByAssignedToID = `-- name: GetTaskByAssignedToID :many
SELECT
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
FROM
    tasks
WHERE
    assigned_to_id = $1
ORDER BY
    date DESC
`

func (q *Queries) GetTaskByAssignedToID(ctx context.Context, assignedToID uuid.NullUUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTaskByAssignedToID, assignedToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AssignedToID,
			&i.Title,
			&i.Type,
			&i.Date,
			&i.Status,
			&i.Priority,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
FROM
    tasks
WHERE
    id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AssignedToID,
		&i.Title,
		&i.Type,
		&i.Date,
		&i.Status,
		&i.Priority,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskDueToday = `-- name: GetTaskDueToday :many
SELECT
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
FROM
    tasks
WHERE
    date::date = current_date
    AND assigned_to_id = $1
    AND STATUS != 'completed'
ORDER BY
    date DESC
`

func (q *Queries) GetTaskDueToday(ctx context.Context, assignedToID uuid.NullUUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTaskDueToday, assignedToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AssignedToID,
			&i.Title,
			&i.Type,
			&i.Date,
			&i.Status,
			&i.Priority,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByContactID = `-- name: GetTasksByContactID :many
SELECT
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
FROM
    tasks
WHERE
    contact_id = $1
ORDER BY
    date DESC
`

func (q *Queries) GetTasksByContactID(ctx context.Context, contactID uuid.NullUUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByContactID, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.AssignedToID,
			&i.Title,
			&i.Type,
			&i.Date,
			&i.Status,
			&i.Priority,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE
    tasks
SET
    contact_id = $2,
    assigned_to_id = $3,
    title = $4,
    TYPE = $5,
    date = $6,
    STATUS = $7,
    priority = $8,
    note = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
`

type UpdateTaskParams struct {
	ID           uuid.UUID
	ContactID    uuid.NullUUID
	AssignedToID uuid.NullUUID
	Title        string
	Type         NullTaskType
	Date         sql.NullTime
	Status       NullTaskStatus
	Priority     NullTaskPriority
	Note         sql.NullString
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.ContactID,
		arg.AssignedToID,
		arg.Title,
		arg.Type,
		arg.Date,
		arg.Status,
		arg.Priority,
		arg.Note,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AssignedToID,
		&i.Title,
		&i.Type,
		&i.Date,
		&i.Status,
		&i.Priority,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE
    tasks
SET
    STATUS = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, contact_id, assigned_to_id, title, type, date, status, priority, note, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID
	Status NullTaskStatus
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.AssignedToID,
		&i.Title,
		&i.Type,
		&i.Date,
		&i.Status,
		&i.Priority,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
