// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webhooks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const landingPageEmails = `-- name: LandingPageEmails :one
INSERT INTO
    contacts (first_name, last_name, source, owner_id)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, first_name, last_name, birthdate, source, status, address, city, state, zip_code, lender, price_range, timeframe, owner_id, created_at, updated_at, last_contacted_at
`

type LandingPageEmailsParams struct {
	FirstName string
	LastName  string
	Source    sql.NullString
	OwnerID   uuid.NullUUID
}

func (q *Queries) LandingPageEmails(ctx context.Context, arg LandingPageEmailsParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, landingPageEmails,
		arg.FirstName,
		arg.LastName,
		arg.Source,
		arg.OwnerID,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Birthdate,
		&i.Source,
		&i.Status,
		&i.Address,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Lender,
		&i.PriceRange,
		&i.Timeframe,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastContactedAt,
	)
	return i, err
}
